/** Demo Instrument
*
*	This patch is a demonstration of the most basic HISE features.
*/


bgImage = Content.addImage("bgImage", 143, 26);
// [JSON bgImage]
Content.setPropertiesFromJSON("bgImage", {
  "x": 0,
  "y": 0,
  "width": 700,
  "height": 450,
  "fileName": "{PROJECT_FOLDER}bg.png"
});
// [/JSON bgImage]

// Set the size of the interface
Content.setHeight(bgImage.get("height"));
Content.setWidth(bgImage.get("width"));

// Tell the engine to use this script as main interface
Synth.addToFront(true);

// This creates an object that controls the Convolution Reverb below
ConvolutionReverb = Synth.getEffect("Convolution Reverb");

// This is autogenerated metadata (but can be edited)
// [JSON bgPanel]
Content.setPropertiesFromJSON("bgPanel", {
  "width": 580,
  "height": 280,
  "itemColour": 822083583,
  "itemColour2": 813727872
});
// [/JSON bgPanel]

// Ads a slider that controls the Volume
volumeSlider = Content.addKnob("volumeSlider", 150, 128);
// [JSON volumeSlider]
Content.setPropertiesFromJSON("volumeSlider", {
  "text": "Volume",
  "min": -100,
  "max": 0,
  "mode": "Decibel",
  "stepSize": 0.10000000000000001,
  "middlePosition": -12
});
// [/JSON volumeSlider]


// Set the key colours randomly
for(i = 0; i < 50; i++)
{
	Engine.setKeyColour(i, 0x88000000);
}

for(i = 50; i < 90; i++)
{
	Engine.setKeyColour(i, 0x22ffffff);
}

for(i = 90; i < 128; i++)
{
	Engine.setKeyColour(i, 0x88000000);
}

// Set the lowest visible key
Engine.setLowestKeyToDisplay(28);



velocityLabel = Content.addLabel("velocityLabel", 125, 202);
// [JSON velocityLabel]
Content.setPropertiesFromJSON("velocityLabel", {
  "text": "Velocity Editor",
  "fontStyle": "Bold",
  "editable": false,
  "multiline": false
});
// [/JSON velocityLabel]
const var sineVolume = Content.addKnob("sineVolume", 218, 261);

ScriptFX = Synth.getEffect("Script FX");function onNoteOn()
{
	
}
function onNoteOff()
{
	
}
function onController()
{
	
}
function onTimer()
{
	
}
function onControl(number, value)
{
}
