/*  ===========================================================================
*
*   This file is part of HISE.
*   Copyright 2016 Christoph Hart
*
*   HISE is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   HISE is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with HISE.  If not, see <http://www.gnu.org/licenses/>.
*
*   Commercial licenses for using HISE in an closed source project are
*   available on request. Please visit the project's website to get more
*   information about commercial licensing:
*
*   http://www.hise.audio/
*
*   HISE is based on the JUCE library,
*   which must be separately licensed for closed source applications:
*
*   http://www.juce.com
*
*   ===========================================================================
*/

#pragma once

namespace hise {
using namespace juce;

class UIComponentDatabase
{
public:

	struct CommonData
	{
		struct Data
		{
			Data();

			BackendProcessor bp;
			JavascriptMidiProcessor jmp;
			ReferenceCountedArray<ScriptingApi::Content::ScriptComponent> list;

			Array<Identifier> commonIds;

		};

		ScriptComponent* getComponentForURL(const String& url, bool forceModuleWildcard, String idPrefix);

		String getComponentIDFromURL(const String& url, bool forceModuleWildcard, String idPrefix);

		SharedResourcePointer<Data> d;
	};

	struct ItemGenerator : public CommonData,
		public MarkdownDataBase::ItemGeneratorBase
	{
		ItemGenerator(File root) :
			ItemGeneratorBase(root)
		{}

		MarkdownDataBase::Item createRootItem(MarkdownDataBase& parent) override;
	};

	struct Resolver : public CommonData,
		public MarkdownParser::LinkResolver
	{
		Resolver(File root_);


		MarkdownParser::ResolveType getPriority() const override { return MarkdownParser::ResolveType::Autogenerated; }
		Identifier getId() const override { RETURN_STATIC_IDENTIFIER("UIComponentResolver"); }
		LinkResolver* clone(MarkdownParser* newParent) const override { return new Resolver(root); }

		String getContent(const String& url) override;

		File root;
	};

	struct ScreenshotProvider : public CommonData,
		public MarkdownParser::ImageProvider
	{
		ScreenshotProvider(MarkdownParser* parent);;

		MarkdownParser::ResolveType getPriority() const override { return MarkdownParser::ResolveType::Autogenerated; }
		Identifier getId() const override { RETURN_STATIC_IDENTIFIER("UIScreenshotProvider"); }
		ImageProvider* clone(MarkdownParser* newParent) const override { return new ScreenshotProvider(newParent); }

		Image getImage(const String& url, float width) override;

		LookAndFeel_V3 laf;
	};

	static constexpr char uiComponentWildcard[] = "/ui-components";


};

struct AutogeneratedDocHelpers
{
	void registerAtDatabase(MarkdownDataBase& b, File markdownRoot);
	void registerAtCrawler(DatabaseCrawler& c, File markdownRoot);
};

}