/** Autogenerated Factory class for converted TCC scripts. */

#include <JuceHeader.h>
#include "AdditionalSourceCode.h"

namespace TccConvertedScriptObjects
{
#include "_TccSineGenerator.cpp"
}

void ConvertedTccScriptFactory::registerModules()
{
	registerDspModule<TccConvertedScriptObjects::SineGenerator>();
}

