/*
  ==============================================================================

    This file was auto-generated!

  ==============================================================================
*/

#include "MainComponent.h"

//==============================================================================
MainContentComponent::MainContentComponent() :
	bp(nullptr, nullptr),
	docProcessor(bp.getDocProcessor()),
	b(bp.getDocWindow()),
	ft(bp.getDocProcessor(), nullptr, {})
{
	setLookAndFeel(&laf);

	AutogeneratedDocHelpers::createDocFloatingTile(&ft);

	addAndMakeVisible(ft);

    setSize (1280, 800);
}

MainContentComponent::~MainContentComponent()
{
    
}

void MainContentComponent::paint (Graphics& g)
{
    // (Our component is opaque, so we must completely fill the background with a solid colour)
    g.fillAll (Colour(0xFF393939));

    
}

void MainContentComponent::resized()
{
	ft.setBounds(getLocalBounds());
}
