<?php
// This is an autogenerated PHP file that contains the properties for creating licence keys on your server.
// Upload this file into the same directory as the key generation php.
// Be careful with this file because it contains the private key used for encryption.

$ALLOWED_IP = ""
$PRODUCT_ID = "Demo Project 1.0"

$PRIVATE_KEY_PART_1 = "1a9fac1a75e29aad55d09313c61ec6ef832f56e5963f4ee778def5790979ef73bb616fc7768b0cac2cd0052c9db3cc5df5553dad4ae2096906c0f46a9e3fe189"
$PRIVATE_KEY_PART_2 = "851e5c844d6d0562ad12df62de99e2ad8fecb27bef3c8a855c5acb5d2f61ad4428af4274e09dd60be8598045a2d14c9041c7b6b0dffecaf5d07c36e6668f9b25";

?>